export const challenges = [
	{
		id: 2,
		title: "Verificar si un número es primo",
		difficulty: "Fácil",
		rating: 3,
		categories: ["Lógica", "Matemáticas"],
	},
	{
		id: 5,
		title: "Ordenar array con burbuja",
		difficulty: "Medio",
		rating: 4,
		categories: ["Ordenamiento", "Algoritmos"],
	},
	{
		id: 8,
		title: "Validar tarjeta de crédito con Luhn",
		difficulty: "Difícil",
		rating: 7,
		categories: ["Algoritmos", "Cifrado"],
	},
	{
		id: 9,
		title: "Búsqueda binaria en array ordenado",
		difficulty: "Medio",
		rating: 4,
		categories: ["Búsqueda", "Algoritmos"],
	},
	{
		id: 13,
		title: "Implementar búsqueda en profundidad",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Grafos", "Algoritmos"],
	},
	{
		id: 23,
		title: "Calcular media, mediana y moda",
		difficulty: "Medio",
		rating: 4,
		categories: ["Matemáticas", "Lógica"],
	},
	{
		id: 24,
		title: "Comprimir cadena con codificación RLE",
		difficulty: "Medio",
		rating: 5,
		categories: ["Cadenas de texto", "Cifrado"],
	},
	{
		id: 29,
		title: "Ordenar array por selección",
		difficulty: "Medio",
		rating: 5,
		categories: ["Ordenamiento", "Algoritmos"],
	},
	{
		id: 30,
		title: "Simular autómata celular 1D (Regla 30)",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Algoritmos", "Lógica"],
	},
	{
		id: 34,
		title: "Búsqueda en anchura (BFS) en grafo",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Grafos", "Algoritmos"],
	},
	{
		id: 46,
		title: "Número de caminos en cuadrícula MxN",
		difficulty: "Medio",
		rating: 6,
		categories: ["Matemáticas", "Algoritmos"],
	},
	{
		id: 48,
		title: "Buscar patrones en cadena con KMP",
		difficulty: "Difícil",
		rating: 7,
		categories: ["Algoritmos", "Cadenas de texto"],
	},
	{
		id: 55,
		title: "Simular el cifrado Vigenère",
		difficulty: "Medio",
		rating: 5,
		categories: ["Cifrado", "Algoritmos"],
	},
	{
		id: 59,
		title: "Simular algoritmo de Kruskal",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Grafos", "Algoritmos", "Optimización"],
	},
	{
		id: 67,
		title: "Simular algoritmo de Bellman-Ford",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Grafos", "Algoritmos"],
	},
	{
		id: 73,
		title: "Sumar matrices de NxM",
		difficulty: "Medio",
		rating: 4,
		categories: ["Matrices", "Matemáticas"],
	},
	{
		id: 80,
		title: "Resolver problema del viajante",
		difficulty: "Difícil",
		rating: 9,
		categories: ["Grafos", "Algoritmos", "Optimización"],
	},
	{
		id: 84,
		title: "Encontrar los números felices",
		difficulty: "Medio",
		rating: 4,
		categories: ["Matemáticas", "Algoritmos"],
	},
	{
		id: 89,
		title: "Búsqueda de patrón con KMP",
		difficulty: "Difícil",
		rating: 8,
		categories: ["Cadenas de texto", "Algoritmos"],
	},
	{
		id: 98,
		title: "Simular algoritmo de Edmonds-Karp",
		difficulty: "Difícil",
		rating: 9,
		categories: ["Grafos", "Optimización"],
	},
	{
		id: 101,
		title: "Invertir un array",
		difficulty: "Fácil",
		rating: 2,
		categories: ["Arrays", "Lógica"],
	},
	{
		id: 102,
		title: "Contar vocales en cadena de texto",
		difficulty: "Fácil",
		rating: 2,
		categories: ["Lógica", "Cadenas de texto"],
	},
	{
		id: 103,
		title: "Calcular factorial de un número",
		difficulty: "Fácil",
		rating: 2,
		categories: ["Matemáticas", "Algoritmos"],
	},
	{
		id: 104,
		title: "Encontrar el máximo en un array",
		difficulty: "Fácil",
		rating: 2,
		categories: ["Arrays", "Lógica"],
	},
	{
		id: 105,
		title: "Convertir decimal a binario",
		difficulty: "Fácil",
		rating: 3,
		categories: ["Matemáticas", "Lógica"],
	},
];
